name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create virtualenv
        run: python3 -m venv .venv
      - name : Activate virtualenv
        run: |
          source .venv/bin/activate
          echo "Virtual Env: $VIRTUAL_ENV"
      - name: Install dependencies
        run: poetry install
      - name: Stop the server
        run: pm2 stop things_backend 2> /dev/null
      - name: Start the server
        run: |
          source .venv/bin/activate
          pm2 start things_backend/main.py --name things_backend
      - name: Save pm2 process
        run: pm2 save