name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install
      - name: Start the server
        run: pm2 stop things_backend 2> /dev/null || true && pm2 start things_backend/main.py --name things_backend
      - name: Save pm2 process
        run: pm2 save