name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create virtualenv
        run: python3 -m venv .venv
      - name : Activate virtualenv
        run: |
          source .venv/bin/activate
          echo "Virtual Env: $VIRTUAL_ENV"
      - name: Install dependencies
        run: poetry install
      - name: Create .env from secret
        run: |
          echo "MQTT_BROKER_HOST=${{ secrets.MQTT_BROKER_HOST }}" >> .env
          echo "MQTT_BROKER_PORT=${{ secrets.MQTT_BROKER_PORT }}" >> .env
          echo "MQTT_BROKER_USER=${{ secrets.MQTT_BROKER_USER }}" >> .env
          echo "MQTT_BROKER_PASSWORD=${{ secrets.MQTT_BROKER_PASSWORD }}" >> .env
      - name: Launch Tests
        run: make test
      - name: Stop the server
        run: pm2 stop things_backend 2> /dev/null
      - name: Start the server
        run: |
          source .venv/bin/activate
          echo "Python Interpreter: $VIRTUAL_ENV/bin/python"
          pm2 start things_backend/main.py --name things_backend --interpreter $VIRTUAL_ENV/bin/python
      - name: Save pm2 process
        run: pm2 save